spring:
  application:
    name: ticket
  datasource:
    url: ${POSTGRES_DEV_URL}
    username: ${POSTGRES_DEV_USERNAME}
    password: ${POSTGRES_DEV_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${TICKET_SCHEMA}
server:
  port: ${TICKET_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}