spring:
  application:
    name: game

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: game_service
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      database: 2

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://13.125.249.226/eureka

slack:
  bot-token: ${SLACK_BOT_TOKEN}