spring:
  application:
    name: game

  datasource:
    url: jdbc:postgresql://3.34.70.47:5432/spoticket
    username: spoticket
    password: spoticket

  jpa:
    properties:
      hibernate:
        default_schema: game_service
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
