spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://13.125.249.226:5432/spoticket
    username: spoticket
    password: spoticket
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_service
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

service:
  jwt:
    access-expiration: 360000
    secret-key: "67mE67CA7J6F64uI64ukIOuLpOuTpCDsp4DsvJzso7zshLjsmpQ="