spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://13.125.249.226:5432/spoticket
    username: spoticket
    password: spoticket
  jpa:
    properties:
      hibernate:
        default_schema: payment_service
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka