spring:
  jpa:
    properties:
      hibernate:
        default_schema: ${PAYMENT_SCHEMA}
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
--- #dev 설정(개발 환경) : db-docker-local 프로필을 설정해줍니다
spring:
  config:
    activate:
      on-profile: "db-docker-local"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
--- # production 설정(실제 운영 환경) : db-aws 프로필을 설정해줍니다
spring:
  config:
    activate:
      on-profile: "db-aws"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DEV_URL}
    username: ${POSTGRES_DEV_USERNAME}
    password: ${POSTGRES_DEV_PASSWORD}



