spring:
  application:
    name: payment

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: payment_service
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      database: 3

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://spoticket-lb-368000243.ap-northeast-2.elb.amazonaws.com/eureka

toss:
  api:
    toss_secret: ${TOSS_API_SECRET}