spring:
  application:
    name: team-stadium

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: team_stadium_service
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      database: 1

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://spoticket-lb-368000243.ap-northeast-2.elb.amazonaws.com/eureka