spring:
  application:
    name: team-stadium
  datasource:
    url: jdbc:postgresql://13.125.249.226:5432/spoticket
    username: spoticket
    password: spoticket
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: team_stadium_service
  data:
    redis:
      host: 13.125.249.226
      port: 6379
      password: default
      database: 1
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka